// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25.04.2026 02:23:49
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/plugins/**/*.{js,ts,mjs}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/composables/**/*.{js,ts,mjs}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/utils/**/*.{js,ts,mjs}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/app.config.{js,ts,mjs}","C:/Users/Umut/OneDrive/Masaüstü/karaytu-starter/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;